package wrteam.multivendor.customer.helper

object Constant {

    //MODIFICATION PART

    //MODIFICATION PART

    //Admin panel url with it would be necessary to put "/"(slash) at end of the url (https://admin.panel.url/)
  //const val MainBaseUrl = "https://gpn.graymatterworks.com/"
  const val MainBaseUrl = "https://gpn.graymatterworks.com/"

    //Admin panel url or ecart multivendor website url (if exist) url with it would be necessary to put "/"(slash) at end of the url (https://admin.panel.url/)
    const val WebSiteUrl = "ecart_website_url_or_admin_panel_url_here"

    //Set your jwt secret key here...key must same in PHP and Android
    const val JWT_KEY = "gmworks"

    //Category View Number Of Grid Per Line
    const val GRID_COLUMN = 3

    //Load items limit in listing ,Maximum load item once
    const val LOAD_ITEM_LIMIT = 10

    //Set true if you want to show sellers in home page, set false if you want to hide the seller in home page
    const val SHOW_SELLERS_IN_HOME_PAGE = true

    //Set your language code here (Follow documentation)
    const val LANGUAGE_CODE = "en"

    //MODIFICATION PART END

    private const val BaseUrl = MainBaseUrl + "api-firebase/"

    //Do not change anything in this link**************************************************
    const val PLAY_STORE_LINK = "https://play.google.com/store/apps/details?id="
    const val PLAY_STORE_RATE_US_LINK = "market://details?id="

    //*************************************************************************************
    //PayTm configs
    const val WEBSITE_LIVE_VAL = "WEB"
    const val INDUSTRY_TYPE_ID_LIVE_VAL = "Retail"
    const val MOBILE_APP_CHANNEL_ID_LIVE_VAL = "WAP"

    //    public static final String PAYTM_ORDER_PROCESS_LIVE_URL = "https://securegw.paytm.in/order/process";
    const val WEBSITE_DEMO_VAL = "WEBSTAGING"
    const val INDUSTRY_TYPE_ID_DEMO_VAL = "Retail"
    const val MOBILE_APP_CHANNEL_ID_DEMO_VAL = "WAP"
    const val PAYTM_ORDER_PROCESS_DEMO_VAL = "https://securegw-stage.paytm.in/order/process"
    const val GENERATE_PAYTM_CHECKSUM = MainBaseUrl + "paytm/generate-checksum.php"
    const val VALID_TRANSACTION = "$MainBaseUrl/paytm/valid-transction.php"
    const val CALLBACK_URL = "CALLBACK_URL"
    const val CHECKSUMHASH = "CHECKSUMHASH"
    const val ORDER_ID_ = "ORDER_ID"
    const val CHANNEL_ID = "CHANNEL_ID"
    const val INDUSTRY_TYPE_ID = "INDUSTRY_TYPE_ID"
    const val WEBSITE = "WEBSITE"
    const val TXN_AMOUNT = "TXN_AMOUNT"
    const val MID = "MID"

    //**********APIS**********
    const val FAQ_URL = BaseUrl + "get-faqs.php"
    const val INVOICE_URL = MainBaseUrl + "invoice-for-mobile.php"
    const val CATEGORY_URL = BaseUrl + "get-categories.php"
    const val SELLER_URL = BaseUrl + "get-seller-data.php"
    const val GET_RAZORPAY_ORDER_URL = BaseUrl + "create-razorpay-order.php"
    const val GET_SUB_CATEGORY_URL = BaseUrl + "get-subcategories.php"
    const val GET_SECTION_URL = BaseUrl + "sections.php"
    const val GET_ADDRESS_URL = BaseUrl + "user-addresses.php"
    const val REGISTER_URL = BaseUrl + "user-registration.php"
    const val PAPAL_URL = MainBaseUrl + "paypal/create-payment.php"
    const val LOGIN_URL = BaseUrl + "login.php"
    const val GET_ALL_DATA_URL = BaseUrl + "get-all-data.php"
    const val GET_PRODUCTS_URL = BaseUrl + "get-products.php"
    const val GET_SELLER_DATA_URL = BaseUrl + "get-seller-data.php"
    const val SETTING_URL = BaseUrl + "settings.php"
    const val GET_FAVORITES_URL = BaseUrl + "favorites.php"
    const val MIDTRANS_PAYMENT_URL = MainBaseUrl + "midtrans/create-payment.php"
    const val GET_LOCATIONS_URL = BaseUrl + "get-locations.php"
    const val ORDER_PROCESS_URL = BaseUrl + "order-process.php"
    const val USER_DATA_URL = BaseUrl + "get-user-data.php"
    const val CART_URL = BaseUrl + "cart.php"
    const val STRIPE_BASE_URL = MainBaseUrl + "stripe/create-payment.php"
    const val TRANSACTION_URL = BaseUrl + "get-user-transactions.php"
    const val PROMO_CODE_CHECK_URL = BaseUrl + "validate-promo-code.php"
    const val VERIFY_PAYMENT_REQUEST = BaseUrl + "payment-request.php"
    const val REGISTER_DEVICE_URL = BaseUrl + "store-fcm-id.php"

    //**************parameters***************
    const val VERIFY_PAYSTACK = "verify_paystack_transaction"
    const val AccessKey = "accesskey"
    const val AccessKeyVal = "90336"
    const val PROFILE = "profile"
    const val UPLOAD_PROFILE = "upload_profile"
    const val GetVal = "1"
    const val GET_PIN_CODES = "get_pincodes"
    const val GET_CITIES = "get_cities"
    const val GET_AREAS = "get_areas"
    const val GROSS_AMOUNT = "gross_amount"
    const val AUTHORIZATION = "Authorization"
    const val PARAMS = "params"
    const val GET_SELECTED_PINCODE = "get_selected_pincode"
    const val GET_SELECTED_PINCODE_NAME = "get_selected_pincode_name"
    const val GET_SELECTED_PINCODE_ID = "get_selected_pincode_id"
    const val IS_USER_LOGIN = "is_user_login"
    const val GET_PRIVACY = "get_privacy"
    const val GET_TERMS = "get_terms"
    const val GET_ADDRESSES = "get_addresses"
    const val DELETE_ADDRESS = "delete_address"
    const val ADD_ADDRESS = "add_address"
    const val UPDATE_ADDRESS = "update_address"
    const val GET_CONTACT = "get_contact"
    const val GET_ABOUT_US = "get_about_us"
    const val NEW_BALANCE = "new_balance"
    const val ADD_TO_FAVORITES = "add_to_favorites"
    const val REMOVE_FROM_FAVORITES = "remove_from_favorites"
    const val RECEIVED = "received"
    const val SHIPPED = "shipped"
    const val PROCESSED = "processed"
    const val DELIVERED = "delivered"
    const val GET_NOTIFICATIONS = "get-notifications"
    const val GET_USER_DATA = "get_user_data"
    const val BALANCE = "balance"
    const val AWAITING_PAYMENT = "awaiting_payment"
    const val KEY_WALLET_USED = "wallet_used"
    const val WALLET_BALANCE = "wallet_balance"
    const val DELIVERY_CHARGE = "delivery_charge"
    const val WALLET = "wallet"
    const val UPDATE_ORDER_STATUS = "update_order_status"
    const val PAYMENT = "payment"
    const val REDIRECT_URL = "redirect_url"
    const val URL = "url"
    const val ADD_MULTIPLE_ITEMS = "add_multiple_items"
    const val SAVE_FOR_LATER_ITEMS = "save_for_later_items"
    const val GET_REORDER_DATA = "get_reorder_data"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val PAYER_EMAIL = "payer_email"
    const val COUNTRY_CODE = "country_code"
    const val COUNTRY = "country"
    const val IS_DEFAULT = "is_default"
    const val ITEM_NAME = "item_name"
    const val ITEM_NUMBER = "item_number"
    const val ORDER_ITEM_ID = "order_item_id"
    const val TRACK_ORDER = "track_order"
    const val SHIPMENT_ID = "shipment_id"
    const val PAYMENT_METHODS = "payment_methods"
    const val RAZOR_PAY_KEY = "razorpay_key"
    const val paystack_public_key = "paystack_public_key"
    const val UNREAD_NOTIFICATION_COUNT = "unread_notification_count"
    const val UNREAD_WALLET_COUNT = "unread_wallet_count"
    const val UNREAD_TRANSACTION_COUNT = "unread_transaction_count"
    const val flutterwave_public_key = "flutterwave_public_key"
    const val flutterwave_secret_key = "flutterwave_secret_key"
    const val flutterwave_encryption_key = "flutterwave_encryption_key"
    const val flutterwave_currency_code = "flutterwave_currency_code"
    const val CITY_ID = "city_id"
    const val PINCODE_ID = "pincode_id"
    const val PINCODE = "pincode"
    const val PINCODES = "pincodes"
    const val CITY = "city"
    const val AREA_ID = "area_id"
    const val AREA_NAME = "area_name"
    const val CITY_NAME = "city_name"
    const val REFERRAL_CODE = "referral_code"
    const val FRIEND_CODE = "friends_code"
    const val SOLD_OUT_TEXT = "Sold Out"
    const val QTY = "qty"
    const val GET_USER_CART = "get_user_cart"
    const val GET_SHIPPING_TYPE = "get_shipping_type"
    const val SHIPPING_TYPE = "shipping_type"
    const val DELETE_ORDER = "delete_order"
    const val GET_USER_TRANSACTION = "get_user_transactions"
    const val TYPE_TRANSACTION = "transactions"
    const val TYPE_WALLET_TRANSACTION = "wallet_transactions"
    const val SUCCESS = "success"
    const val FAILED = "failed"
    const val PENDING = "pending"
    const val CREDIT = "credit"
    const val SAVE_FOR_LATER = "save_for_later"
    const val REMOVE_FROM_CART = "remove_from_cart"
    const val SORT = "sort"
    const val TYPE = "type"
    const val IMAGE = "image"
    const val NAME = "name"
    const val ID = "id"
    const val VARIANT_POSITION = "variantPosition"
    const val LIST_POSITION = "list_position"
    const val SUBTITLE = "subtitle"
    const val PRODUCTS = "products"
    const val STATUS = "status"
    const val TITLE = "title"
    const val SECTION_STYLE = "style"
    const val SHORT_DESC = "short_description"
    const val REGISTER = "register"
    const val EMAIL = "email"
    const val MOBILE = "mobile"
    const val LOGIN = "login"
    const val ALTERNATE_MOBILE = "alternate_mobile"
    const val PASSWORD = "password"
    const val FCM_ID = "fcm_id"
    const val GET_ALL_PRODUCTS_NAME = "get_all_products_name"
    const val GET_ALL_PRODUCTS = "get_all_products"
    const val CHECK_DELIEVABILITY = "check_deliverability"
    const val STATE = "state"
    const val ERROR = "error"
    const val GET_TIMEZONE = "get_timezone"
    const val ORDER_NOTE = "order_note"
    const val VERIFY_USER = "verify-user"
    const val USER_ID = "user_id"
    const val GET_PROMO_CODES = "get_promo_codes"
    const val ADD_WALLET_BALANCE = "add_wallet_balance"
    const val TAX_PERCENT = "tax_percentage"
    const val SELLER_ID = "seller_id"
    const val GET_SELLER_DATA = "get_seller_data"
    const val EDIT_PROFILE = "edit-profile"
    const val CHANGE_PASSWORD = "change-password"
    const val FORGOT_PASSWORD_MOBILE = "forgot-password-mobile"
    const val CATEGORY_ID = "category_id"
    const val CATEGORIES = "categories"
    const val SLIDER_IMAGES = "slider_images"
    const val SELLER = "seller"
    const val SECTIONS = "sections"
    const val OFFER_IMAGES = "offer_images"
    const val CATEGORY_OFFER_IMAGES = "category_offer_images"
    const val SLIDER_OFFER_IMAGES = "slider_offer_images"
    const val SELLER_OFFER_IMAGES = "seller_offer_images"
    const val SUB_CATEGORY_ID = "subcategory_id"
    const val GET_ALL_SECTIONS = "get-all-sections"
    const val SECTION_ID = "section_id"
    const val GET_FAVORITES = "get_favorites"
    const val GET_PRODUCTS_OFFLINE = "get_products_offline"
    const val GET_VARIANTS_OFFLINE = "get_variants_offline"
    const val SEARCH = "search"
    const val ADD_TRANSACTION = "add_transaction"
    const val GET_PAYMENT_METHOD = "get_payment_methods"
    const val GET_ORDERS = "get_orders"
    const val CONTACT = "contact"
    const val DATA = "data"
    const val ITEMS = "items"
    const val PRODUCT_ID = "product_id"
    const val GET_SIMILAR_PRODUCT = "get_similar_products"
    const val PRODUCT_IDs = "product_ids"
    const val VARIANT_IDs = "variant_ids"
    const val SETTINGS = "settings"
    const val CANCELLED = "cancelled"
    const val RETURNED = "returned"
    const val GET_TIME_SLOT_CONFIG = "get_time_slot_config"
    const val TIME_SLOT_CONFIG = "time_slot_config"
    const val IS_TIME_SLOTS_ENABLE = "is_time_slots_enabled"
    const val DELIVERY_STARTS_FROM = "delivery_starts_from"
    const val ALLOWED_DAYS = "allowed_days"
    const val paypal_method = "paypal_payment_method"
    const val razor_pay_method = "razorpay_payment_method"
    const val cod_payment_method = "cod_payment_method"
    const val product = "product"
    const val cod_mode = "cod_mode"
    const val paystack_method = "paystack_payment_method"
    const val flutterwave_payment_method = "flutterwave_payment_method"
    const val midtrans_payment_method = "midtrans_payment_method"
    const val stripe_payment_method = "stripe_payment_method"
    const val paytm_payment_method = "paytm_payment_method"
    const val ssl_commerce_payment_method = "ssl_commerce_payment_method"
    const val ssl_commerece_mode = "ssl_commerece_mode"
    const val ssl_commerece_store_id = "ssl_commerece_store_id"
    const val ssl_commerece_secret_key = "ssl_commerece_secret_key"
    const val direct_bank_transfer_method = "direct_bank_transfer_method"
    const val account_name = "account_name"
    const val account_number = "account_number"
    const val bank_name = "bank_name"
    const val bank_code = "bank_code"
    const val notes = "notes"
    const val paytm_merchant_id = "paytm_merchant_id"
    const val paytm_merchant_key = "paytm_merchant_key"
    const val paytm_mode = "paytm_mode"
    const val maintenance = "maintenance"
    const val DELIVERY_CHARGE_WITH_COD = "delivery_charge_with_cod"
    const val DELIVERY_CHARGE_WITHOUT_COD = "delivery_charge_without_cod"
    const val SAVED_AMOUNT = "saved_amount"
    const val CURRENCY = "currency"
    const val GET_FAQS = "get_faqs"
    const val LIMIT = "limit"
    const val OFFSET = "offset"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val AMOUNT = "amount"
    const val REFERENCE = "reference"
    const val PROMO_DISCOUNT = "promo_discount"
    const val TOTAL = "total"
    const val PRODUCT_VARIANT_ID = "product_variant_id"
    const val QUANTITY = "quantity"
    const val USER_NAME = "user_name"
    const val DELIVERY_TIME = "delivery_time"
    const val ADDRESS_ID = "address_id"
    const val PAYMENT_METHOD = "payment_method"
    const val ADDRESS = "address"
    const val ADDRESS_LINE1 = "address_line1"
    const val POSTAL_CODE = "postal_code"
    const val LANDMARK = "landmark"
    const val TRANS_ID = "txn_id"
    const val MESSAGE = "message"
    const val ESTIMATED_DATE = "estimated_date"
    const val FINAL_TOTAL = "final_total"
    const val FROM = "from"
    const val ORDER_ID = "order_id"
    const val IMAGES = "image[]"
    const val DELETE_BANK_TRANSFER_ATTACHMENT = "delete_bank_transfers_attachment"
    const val UPLOAD_BANK_TRANSFER_ATTACHMENT = "upload_bank_transfers_attachment"
    const val publishableKey = "publishableKey"
    const val clientSecret = "clientSecret"
    const val PLACE_ORDER = "place_order"
    const val NEW = "new"
    const val OLD = "old"
    const val HIGH = "high"
    const val LOW = "low"
    const val SUB_TOTAL = "sub_total"
    const val SLUG = "slug"
    const val PROMO_CODE = "promo_code"
    val filterValues = arrayOf<CharSequence>(
        " Newest to Oldest ",
        " Oldest to Newest ",
        " Price Highest to Lowest ",
        " Price Lowest to Highest "
    )
    const val CUST_ID = "CUST_ID"
    const val ORDERID = "ORDERID"
    const val STATUS_ = "STATUS"
    const val TXN_SUCCESS = "TXN_SUCCESS"
    const val minimum_version_required = "minimum_version_required"
    const val is_version_system_on = "is_version_system_on"
    const val min_order_amount = "min_order_amount"
    const val max_cart_items_count = "max_cart_items_count"
    const val area_wise_delivery_charge = "area_wise_delivery_charge"
    const val is_refer_earn_on = "is_refer_earn_on"
    const val refer_earn_bonus = "refer_earn_bonus"
    const val refer_earn_method = "refer_earn_method"
    const val max_refer_earn_amount = "max_refer_earn_amount"
    const val max_product_return_days = "max_product_return_days"
    const val user_wallet_refill_limit = "user_wallet_refill_limit"
    const val min_refer_earn_order_amount = "min_refer_earn_order_amount"
    private const val ALPHA_NUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghjiklmnopqrstuvwxyz"
    private const val NUMERIC_STRING = "123456789"
    lateinit var TOOLBAR_TITLE: String

    //**************Constants Values***************
    var DefaultAddress = ""
    var selectedAddressId = ""
    var selectedAddress = ""
    var DefaultCity = ""
    var DefaultPinCode = ""
    var isCODAllow = true
    var U_ID = ""
    var CartValues = HashMap<String, String>()
    var selectedDatePosition = 0
    var FLOAT_TOTAL_AMOUNT = 0.0
    var TOTAL_CART_ITEM = 0
    var orderPlaceable = true
    var PAYPAL = ""
    var RAZORPAY = ""
    var COD = ""
    var COD_MODE = ""
    var PAYSTACK = ""
    var FLUTTERWAVE = ""
    var MIDTRANS = ""
    var STRIPE = ""
    var PAYTM_MERCHANT_ID = ""
    var PAYTM = ""
    var PAYTM_MERCHANT_KEY = ""
    var PAYTM_MODE = ""
    var RAZOR_PAY_KEY_VALUE = ""
    var PAYSTACK_KEY = ""
    var FLUTTERWAVE_PUBLIC_KEY_VAL = ""
    var FLUTTERWAVE_SECRET_KEY_VAL = ""
    var FLUTTERWAVE_ENCRYPTION_KEY_VAL = ""
    var FLUTTERWAVE_CURRENCY_CODE_VAL = ""
    var SSLECOMMERZ = ""
    var SSLECOMMERZ_MODE = ""
    var SSLECOMMERZ_STORE_ID = ""
    var SSLECOMMERZ_SECRET_KEY = ""
    var DIRECT_BANK_TRANSFER = ""
    var ACCOUNT_NAME = ""
    var ACCOUNT_NUMBER = ""
    var BANK_NAME = ""
    var BANK_CODE = ""
    var NOTES = ""
    var homeClicked = false
    var categoryClicked = false
    var favoriteClicked = false
    var drawerClicked = false
    fun randomAlphaNumeric(count: Int): String {
        var count1 = count
        val builder = StringBuilder()
        while (count1-- != 0) {
            val character = (Math.random() * ALPHA_NUMERIC_STRING.length).toInt()
            builder.append(ALPHA_NUMERIC_STRING[character])
        }
        return builder.toString()
    }

    fun randomNumeric(count: Int): String {
        var count1 = count
        val builder = StringBuilder()
        while (count1-- != 0) {
            val character = (Math.random() * NUMERIC_STRING.length).toInt()
            builder.append(NUMERIC_STRING[character])
        }
        return builder.toString()
    }
}